### ISSUE TITLE
Maxify does not recreate _id properly when it is ObjectID 

### ISSUE THREAD

**Issue by GunnarSturla** [GroundMeteor/minimax#5]
I have a collection where the `_id`s are Mongo ObectID's and kept getting `Error: Meteor does not currently support objects other than ObjectID as ids`. 

A colleague of mine and I located the error in minimax's method of maxifying `_id`s; they are recreated as regular Objects with `_str`attribute, which minimongo does not accept.

Our solution was adding a check to see if the document being maxified had an `_id._str` attribute and in those cases recreate the `_id` as `Meteor.Collection.ObectID(_id._str)`

I'll send a pull request shortly with our fix, but I thought I'd create an issue first

**Comment by raix** [comment]
I minimax doesn't know about mongodb - it just minifies/maxifies objects.

This could be done in the core `EJSON.stringify` but MDG will prop. not tie it to a mongo specific type. One could perhaps create a `ObjectID` EJSON type.

You could ask @glasser if they'd take a pr on this or if they have any suggestions, it could be converting ID's from the remote mongo driver - or if minimongo should support `_id._str`.

Kind regards Morten

**Comment by raix** [comment]
it's sort of related to https://github.com/GroundMeteor/db/issues/82
`lists.insert({'_id':new Mongo.Collection.ObjectID(),'name':name});`

**Comment by GunnarSturla** [comment]
Yeah, it looks like GroundMeteor/db#82 is the same issue.

I find it unlikely that MDG would change minimongo's handling of `_id`'s since it' specifically stated that `_id`'s need to be either `String` or `ObjectID`. (I recall reading but could not find in the docs). 

Do you think that creating a custom/[user created EJSON type](http://docs.meteor.com/#/full/ejson_add_type) would be the way to go?

**Comment by raix** [comment]
@GunnarSturla might be more performant
